/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MisComprasRouteImport } from './routes/mis-compras'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as MisComprasIndexRouteImport } from './routes/mis-compras.index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as ProductosProductoIDRouteImport } from './routes/productos.$productoID'
import { Route as MisComprasOrderIdRouteImport } from './routes/mis-compras.$orderId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MisComprasRoute = MisComprasRouteImport.update({
  id: '/mis-compras',
  path: '/mis-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MisComprasIndexRoute = MisComprasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MisComprasRoute,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosProductoIDRoute = ProductosProductoIDRouteImport.update({
  id: '/productos/$productoID',
  path: '/productos/$productoID',
  getParentRoute: () => rootRouteImport,
} as any)
const MisComprasOrderIdRoute = MisComprasOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => MisComprasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mis-compras': typeof MisComprasRouteWithChildren
  '/register': typeof RegisterRoute
  '/mis-compras/$orderId': typeof MisComprasOrderIdRoute
  '/productos/$productoID': typeof ProductosProductoIDRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/mis-compras/': typeof MisComprasIndexRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/mis-compras/$orderId': typeof MisComprasOrderIdRoute
  '/productos/$productoID': typeof ProductosProductoIDRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/mis-compras': typeof MisComprasIndexRoute
  '/productos': typeof ProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mis-compras': typeof MisComprasRouteWithChildren
  '/register': typeof RegisterRoute
  '/mis-compras/$orderId': typeof MisComprasOrderIdRoute
  '/productos/$productoID': typeof ProductosProductoIDRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/mis-compras/': typeof MisComprasIndexRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrito'
    | '/categorias'
    | '/contacto'
    | '/forgot-password'
    | '/login'
    | '/mis-compras'
    | '/register'
    | '/mis-compras/$orderId'
    | '/productos/$productoID'
    | '/reset-password/$token'
    | '/mis-compras/'
    | '/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrito'
    | '/categorias'
    | '/contacto'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/mis-compras/$orderId'
    | '/productos/$productoID'
    | '/reset-password/$token'
    | '/mis-compras'
    | '/productos'
  id:
    | '__root__'
    | '/'
    | '/carrito'
    | '/categorias'
    | '/contacto'
    | '/forgot-password'
    | '/login'
    | '/mis-compras'
    | '/register'
    | '/mis-compras/$orderId'
    | '/productos/$productoID'
    | '/reset-password/$token'
    | '/mis-compras/'
    | '/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarritoRoute: typeof CarritoRoute
  CategoriasRoute: typeof CategoriasRoute
  ContactoRoute: typeof ContactoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MisComprasRoute: typeof MisComprasRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ProductosProductoIDRoute: typeof ProductosProductoIDRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-compras': {
      id: '/mis-compras'
      path: '/mis-compras'
      fullPath: '/mis-compras'
      preLoaderRoute: typeof MisComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-compras/': {
      id: '/mis-compras/'
      path: '/'
      fullPath: '/mis-compras/'
      preLoaderRoute: typeof MisComprasIndexRouteImport
      parentRoute: typeof MisComprasRoute
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$productoID': {
      id: '/productos/$productoID'
      path: '/productos/$productoID'
      fullPath: '/productos/$productoID'
      preLoaderRoute: typeof ProductosProductoIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-compras/$orderId': {
      id: '/mis-compras/$orderId'
      path: '/$orderId'
      fullPath: '/mis-compras/$orderId'
      preLoaderRoute: typeof MisComprasOrderIdRouteImport
      parentRoute: typeof MisComprasRoute
    }
  }
}

interface MisComprasRouteChildren {
  MisComprasOrderIdRoute: typeof MisComprasOrderIdRoute
  MisComprasIndexRoute: typeof MisComprasIndexRoute
}

const MisComprasRouteChildren: MisComprasRouteChildren = {
  MisComprasOrderIdRoute: MisComprasOrderIdRoute,
  MisComprasIndexRoute: MisComprasIndexRoute,
}

const MisComprasRouteWithChildren = MisComprasRoute._addFileChildren(
  MisComprasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarritoRoute: CarritoRoute,
  CategoriasRoute: CategoriasRoute,
  ContactoRoute: ContactoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MisComprasRoute: MisComprasRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ProductosProductoIDRoute: ProductosProductoIDRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  ProductosIndexRoute: ProductosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
