/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosProductoIDRouteImport } from './routes/productos.$productoID'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosProductoIDRoute = ProductosProductoIDRouteImport.update({
  id: '/$productoID',
  path: '/$productoID',
  getParentRoute: () => ProductosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/productos': typeof ProductosRouteWithChildren
  '/productos/$productoID': typeof ProductosProductoIDRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/productos': typeof ProductosRouteWithChildren
  '/productos/$productoID': typeof ProductosProductoIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/productos': typeof ProductosRouteWithChildren
  '/productos/$productoID': typeof ProductosProductoIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/contacto'
    | '/productos'
    | '/productos/$productoID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categorias'
    | '/contacto'
    | '/productos'
    | '/productos/$productoID'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/contacto'
    | '/productos'
    | '/productos/$productoID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRoute
  ContactoRoute: typeof ContactoRoute
  ProductosRoute: typeof ProductosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$productoID': {
      id: '/productos/$productoID'
      path: '/$productoID'
      fullPath: '/productos/$productoID'
      preLoaderRoute: typeof ProductosProductoIDRouteImport
      parentRoute: typeof ProductosRoute
    }
  }
}

interface ProductosRouteChildren {
  ProductosProductoIDRoute: typeof ProductosProductoIDRoute
}

const ProductosRouteChildren: ProductosRouteChildren = {
  ProductosProductoIDRoute: ProductosProductoIDRoute,
}

const ProductosRouteWithChildren = ProductosRoute._addFileChildren(
  ProductosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRoute,
  ContactoRoute: ContactoRoute,
  ProductosRoute: ProductosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
